version: '3.3'
services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data
     - /etc/localtime:/etc/localtime:ro
    container_name: portainer
    logging:
      options:
        max-size: 10m

volumes:
   portainer_data:
    external: true
